---
- name: restart sixpack
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - sixpack_server
    - sixpack_web

- name: start nginx
  service: name=nginx state=started

- name: restart nginx
  service: name=nginx state=restarted

- name: restart redis
  service: name=redis-server state=restarted
