redis_port: {{ redis.port }}
redis_host: {{ redis.host }}
redis_prefix: sixpack
redis_db: 15

enable_whiplash: False

# The regex to match for robots
robot_regex: $^|trivial|facebook|MetaURI|butterfly|google|amazon|goldfire|sleuth|xenu|msnbot|SiteUptime|Slurp|WordPress|ZIBB|ZyBorg|pingdom|bot|yahoo|slurp|java|fetch|spider|url|crawl|oneriot|abby|commentreader|twiceler
ignored_ip_addresses: []

asset_path: gen
secret_key: '{{ sixpack.key }}'